var raw = {
    "players": [
        {
            "id": 0,
            "name": "Kamon",
            "css_class": "kamon",
            "creature_ids": [3, 6, 51, 65, 68, 71, 76, 78, 89, 115, 123, 128, 130, 135, 136, 143, 145, 149, 157, 171, 181, 184, 196, 197, 213, 217, 230, 232, 237, 272, 282, 286, 289, 291, 303, 306, 330, 342, 356, 376, 385, 398, 407, 426, 448, 450, 460, 461, 468, 469, 477, 497, 508, 523, 534, 537, 545, 553, 555, 567, 571, 579, 598, 612, 655, 660, 666, 668, 671, 673, 683, 693, 695, 697, 706, 711, 717, 134],
            "trainer_sprite": "../img/giovanni.png"
        }, {
            "id": 1,
            "name": "JaeBird",
            "css_class": "jbird",
            "creature_ids": [9, 26, 38, 47, 73, 80, 82, 91, 94, 101, 103, 106, 110, 131, 142, 144, 154, 169, 176, 208, 210, 212, 214, 227, 229, 233, 235, 242, 248, 251, 254, 260, 308, 344, 350, 437, 464, 465, 466, 467, 473, 479, 503, 530, 560, 561, 606, 609, 623, 625, 628, 635, 637, 658, 681, 685, 691, 699, 702, 703, 707, 709, 713, 716, 547],
            "trainer_sprite": "../img/zen.gif"
        }, {
            "id": 2,
            "name": "Steve",
            "css_class": "steve",
            "creature_ids": [12, 31, 34, 53, 59, 85, 121, 127, 132, 139, 146, 151, 160, 199, 257, 346, 359, 373, 424, 429, 442, 445, 454, 463, 472, 474, 475, 478, 526, 565, 596, 604, 620, 652, 663, 675, 676, 678, 687, 689, 700, 701, 715, 718],
            "trainer_sprite": "../img/Spr_B2W2_Alder.png"
        },
    ],
    "events": [
        {   'date': '2014/01/01 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 2}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/02 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 0, 'win_player_id': 1},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/03 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/04 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 0, 'win_player_id': 1},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/05 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 0, 'win_player_id': 2}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/06 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 0, 'win_player_id': 2},
                                         {'lose_player_id': 1, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/07 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/01/08 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 0},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 1},
                                       {   'creature_ids': [1, 1, 1, 1, 1, 1],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/05/29 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 0, 'win_player_id': 1},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [   612,
                                                               115,
                                                               237,
                                                               149,
                                                               598,
                                                               468],
                                           'player_id': 0},
                                       {   'creature_ids': [   479,
                                                               308,
                                                               658,
                                                               176,
                                                               707,
                                                               110],
                                           'player_id': 1},
                                       {   'creature_ids': [   424,
                                                               445,
                                                               663,
                                                               257,
                                                               475,
                                                               472],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/06/13 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 0, 'win_player_id': 2},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1}],
                          'teams': [   {   'creature_ids': [   598,
                                                               115,
                                                               149,
                                                               134,
                                                               237,
                                                               612],
                                           'player_id': 0},
                                       {   'creature_ids': [   176,
                                                               308,
                                                               479,
                                                               609,
                                                               530,
                                                               248],
                                           'player_id': 1},
                                       {   'creature_ids': [   424,
                                                               663,
                                                               445,
                                                               715,
                                                               53,
                                                               257],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/06/24 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 0, 'win_player_id': 1},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [   303,
                                                               693,
                                                               149,
                                                               448,
                                                               237,
                                                               468],
                                           'player_id': 0},
                                       {   'creature_ids': [   169,
                                                               308,
                                                               479,
                                                               609,
                                                               707,
                                                               212],
                                           'player_id': 1},
                                       {   'creature_ids': [   257,
                                                               445,
                                                               53,
                                                               424,
                                                               663,
                                                               715],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/07/13 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [   303,
                                                               663,
                                                               237,
                                                               149,
                                                               468,
                                                               612],
                                           'player_id': 0},
                                       {   'creature_ids': [   437,
                                                               709,
                                                               703,
                                                               233,
                                                               464,
                                                               248],
                                           'player_id': 1},
                                       {   'creature_ids': [   53,
                                                               445,
                                                               475,
                                                               715,
                                                               59,
                                                               652],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/07/29 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 0, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [   666,
                                                               426,
                                                               237,
                                                               376,
                                                               115,
                                                               693],
                                           'player_id': 0},
                                       {   'creature_ids': [   94,
                                                               560,
                                                               479,
                                                               260,
                                                               707,
                                                               212],
                                           'player_id': 1},
                                       {   'creature_ids': [   663,
                                                               445,
                                                               475,
                                                               424,
                                                               715,
                                                               160],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/08/09 00:00',
            'description': '',
            'kwargs': {   'matches': [   {'lose_player_id': 1, 'win_player_id': 0},
                                         {'lose_player_id': 2, 'win_player_id': 1},
                                         {'lose_player_id': 2, 'win_player_id': 0},
                                         {'lose_player_id': 0, 'win_player_id': 1},
                                         {'lose_player_id': 1, 'win_player_id': 2},
                                         {'lose_player_id': 2, 'win_player_id': 0}],
                          'teams': [   {   'creature_ids': [   534,
                                                               115,
                                                               149,
                                                               598,
                                                               130,
                                                               468],
                                           'player_id': 0},
                                       {   'creature_ids': [   94,
                                                               560,
                                                               707,
                                                               681,
                                                               637,
                                                               479],
                                           'player_id': 1},
                                       {   'creature_ids': [   445,
                                                               257,
                                                               127,
                                                               53,
                                                               424,
                                                               663],
                                           'player_id': 2}]},
            'type': 'tournament'},
        {   'date': '2014/05/10 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 707,
                                               'from_player_id': 0,
                                               'to_player_id': 1},
                                           {   'creature_id': 687,
                                               'from_player_id': 0,
                                               'to_player_id': 1},
                                           {   'creature_id': 695,
                                               'from_player_id': 1,
                                               'to_player_id': 0},
                                           {   'creature_id': 555,
                                               'from_player_id': 1,
                                               'to_player_id': 0},
                                           {   'creature_id': 460,
                                               'from_player_id': 1,
                                               'to_player_id': 0}]},
            'type': 'trade'},
        {   'date': '2014/05/24 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 424,
                                               'from_player_id': 1,
                                               'to_player_id': 2},
                                           {   'creature_id': 472,
                                               'from_player_id': 1,
                                               'to_player_id': 2},
                                           {   'creature_id': 38,
                                               'from_player_id': 2,
                                               'to_player_id': 1}]},
            'type': 'trade'},
        {   'date': '2014/06/13 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 229,
                                               'from_player_id': 2,
                                               'to_player_id': 1},
                                           {   'creature_id': 121,
                                               'from_player_id': 1,
                                               'to_player_id': 2}]},
            'type': 'trade'},
        {   'date': '2014/07/10 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 663,
                                               'from_player_id': 2,
                                               'to_player_id': 0},
                                           {   'creature_id': 376,
                                               'from_player_id': 0,
                                               'to_player_id': 2}]},
            'type': 'trade'},
        {   'date': '2014/07/17 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 663,
                                               'from_player_id': 0,
                                               'to_player_id': 2},
                                           {   'creature_id': 376,
                                               'from_player_id': 2,
                                               'to_player_id': 0},
                                           {   'creature_id': 136,
                                               'from_player_id': 2,
                                               'to_player_id': 0}]},
            'type': 'trade'},
        {   'date': '2014/07/30 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 628,
                                               'from_player_id': 2,
                                               'to_player_id': 1},
                                           {   'creature_id': 687,
                                               'from_player_id': 1,
                                               'to_player_id': 2}]},
            'type': 'trade'},
        {   'date': '2014/07/31 00:00',
            'description': '',
            'kwargs': {   'creatures': [   {   'creature_id': 142,
                                               'from_player_id': 0,
                                               'to_player_id': 1},
                                           {   'creature_id': 545,
                                               'from_player_id': 1,
                                               'to_player_id': 0}]},
            'type': 'trade'},
        {   'date': '2013/09/01',
            'description': 'Gen 6 draft',
            'kwargs': {   'creatures_drafted': [   {'creature_id': 697, 'player_id': 0},
                                                   {'creature_id': 681, 'player_id': 1},
                                                   {'creature_id': 663, 'player_id': 2},
                                                   {'creature_id': 693, 'player_id': 0},
                                                   {'creature_id': 691, 'player_id': 1},
                                                   {'creature_id': 715, 'player_id': 2},
                                                   {'creature_id': 707, 'player_id': 0},
                                                   {'creature_id': 706, 'player_id': 1},
                                                   {'creature_id': 689, 'player_id': 2},
                                                   {'creature_id': 673, 'player_id': 0},
                                                   {'creature_id': 666, 'player_id': 1},
                                                   {'creature_id': 709, 'player_id': 2},
                                                   {'creature_id': 687, 'player_id': 0},
                                                   {'creature_id': 695, 'player_id': 1},
                                                   {'creature_id': 700, 'player_id': 2},
                                                   {'creature_id': 675, 'player_id': 0},
                                                   {'creature_id': 703, 'player_id': 1},
                                                   {'creature_id': 676, 'player_id': 2},
                                                   {'creature_id': 711, 'player_id': 0},
                                                   {'creature_id': 699, 'player_id': 1},
                                                   {'creature_id': 713, 'player_id': 2},
                                                   {'creature_id': 671, 'player_id': 0},
                                                   {'creature_id': 685, 'player_id': 1},
                                                   {'creature_id': 701, 'player_id': 2},
                                                   {'creature_id': 668, 'player_id': 0},
                                                   {'creature_id': 678, 'player_id': 1},
                                                   {'creature_id': 683, 'player_id': 2},
                                                   {'creature_id': 680, 'player_id': 0},
                                                   {'creature_id': 702, 'player_id': 1},
                                                   {'creature_id': 660, 'player_id': 2},
                                                   {'creature_id': 717, 'player_id': 0},
                                                   {'creature_id': 716, 'player_id': 1},
                                                   {   'creature_id': 718,
                                                       'player_id': 2}]},
            'type': 'draft'},
        {
            "type": "champion",
            "date": "2014/11/26 23:00",
            "description": 'Kamon wins Season 2! Kangaskhan is named Season 2 MVP.',
            "kwargs": {
                "mvp_creature_id": 115,
                "teams": [
                    {
                        "player_id": 0,
                        "creature_ids": [237, 149, 115, 468, 612, 598],
                    }, {
                        "player_id": 1,
                        "creature_ids": [479, 94, 560, 212, 248, 681],
                    }, {
                        "player_id": 2,
                        "creature_ids": [663, 445, 424, 257, 53, 475],
                    }
                ],
            }
        }
    ],
    "creatures": ['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon', 'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool', 'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash', 'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', 'Farfetch’d', 'Doduo', 'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute', 'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey', 'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair', 'Dragonite', 'Mewtwo', 'Mew', 'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw', 'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn', 'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu', 'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora', 'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow', 'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Snubbull', 'Granbull', 'Qwilfish', 'Scizor', 'Shuckle', 'Heracross', 'Sneasel', 'Teddiursa', 'Ursaring', 'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour', 'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey', 'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi', 'Treecko', 'Grovyle', 'Sceptile', 'Torchic', 'Combusken', 'Blaziken', 'Mudkip', 'Marshtomp', 'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir', 'Surskit', 'Masquerain', 'Shroomish', 'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask', 'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita', 'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron', 'Lairon', 'Aggron', 'Meditite', 'Medicham', 'Electrike', 'Manectric', 'Plusle', 'Minun', 'Volbeat', 'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda', 'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu', 'Altaria', 'Zangoose', 'Seviper', 'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette', 'Duskull', 'Dusclops', 'Tropius', 'Chimecho', 'Absol', 'Wynaut', 'Snorunt', 'Glalie', 'Spheal', 'Sealeo', 'Walrein', 'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon', 'Salamence', 'Beldum', 'Metang', 'Metagross', 'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza', 'Jirachi', 'Deoxys', 'Turtwig', 'Grotle', 'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup', 'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor', 'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio', 'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon', 'Bastiodon', 'Burmy', 'Wormadam', 'Mothim', 'Combee', 'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos', 'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary', 'Lopunny', 'Mismagius', 'Honchkrow', 'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb', 'Gible', 'Gabite', 'Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Hippopotas', 'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak', 'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover', 'Abomasnow', 'Weavile', 'Magnezone', 'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar', 'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor', 'Mamoswine', 'Porygon-Z', 'Gallade', 'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas', 'Giratina', 'Cresselia', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin', 'Arceus', 'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite', 'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog', 'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard', 'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour', 'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant', 'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith', 'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole', 'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon', 'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee', 'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile', 'Krokorok', 'Krookodile', 'Darumaka', 'Darmanitan', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy', 'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga', 'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor', 'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita', 'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett', 'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling', 'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus', 'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik', 'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang', 'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem', 'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure', 'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet', 'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon', 'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet', 'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino', 'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion', 'Terrakion', 'Virizion', 'Tornadus', 'Thundurus', 'Reshiram', 'Zekrom', 'Landorus', 'Kyurem', 'Keldeo', 'Meloetta', 'Genesect', 'Chespin', 'Quilladin', 'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie', 'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling', 'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon', 'Litleo', 'Pyroar', 'Flabébé', 'Floette', 'Florges', 'Skiddo', 'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr', 'Meowstic', 'Honedge', 'Doublade', 'Aegislash', 'Spritzee', 'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle', 'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer', 'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura', 'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy', 'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant', 'Pumpkaboo', 'Gourgeist', 'Bergmite', 'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal', 'Zygarde', 'Diancie', 'Hoopa', 'Volcanion', 'Rowlet', 'Dartrix', 'Decidueye', 'Litten', 'Torracat', 'Incineroar', 'Popplio', 'Brionne', 'Primarina', 'Pikipek', 'Trumbeak', 'Toucannon', 'Yungoos', 'Gumshoos', 'Grubbin', 'Charjabug', 'Vikavolt', 'Crabrawler', 'Crabominable', 'Oricorio', 'Cutiefly', 'Ribombee', 'Rockruff', 'Lycanroc', 'Wishiwashi', 'Mareanie', 'Toxapex', 'Mudbray', 'Mudsdale', 'Dewpider', 'Araquanid', 'Fomantis', 'Lurantis', 'Morelull', 'Shiinotic', 'Salandit', 'Salazzle', 'Stufful', 'Bewear', 'Bounsweet', 'Steenee', 'Tsareena', 'Comfey', 'Oranguru', 'Passimian', 'Wimpod', 'Golisopod', 'Sandygast', 'Palossand', 'Pyukumuku', 'Type: Null', 'Silvally', 'Minior', 'Komala', 'Turtonator', 'Togedemaru', 'Mimikyu', 'Bruxish', 'Drampa', 'Dhelmise', 'Jangmo-o', 'Hakamo-o', 'Kommo-o', 'Tapu Koko', 'Tapu Lele', 'Tapu Bulu', 'Tapu Fini', 'Cosmog', 'Cosmoem', 'Solgaleo', 'Lunala', 'Nihilego', 'Buzzwole', 'Pheromosa', 'Xurkitree', 'Celesteela', 'Kartana', 'Guzzlord', 'Necrozma', 'Magearna', 'Marshadow', 'Poipole', 'Naganadel', 'Stakataka', 'Blacephalon', 'Zeraora', 'Meltan', 'Melmetal']
}