// Generated by helper/replay_stats.py -- do not edit by hand.
var replay_stats = {
 "creatures": {
  "1000": {
   "abilities": [],
   "best": {
    "kos": 4,
    "nick": "Gholdengo",
    "pct_dealt": 131.9,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612881760"
   },
   "boosts": 10,
   "by_player": {
    "4": 4
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 5,
   "dmg_dealt": 1465,
   "dmg_taken": 1038,
   "fainted": 2,
   "form": "Gholdengo",
   "forms": [
    [
     "Gholdengo",
     4
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 7,
   "maxhps": [
    [
     316,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 12,
   "name": "Gholdengo",
   "nicknames": [
    [
     "Gholdengo",
     4
    ]
   ],
   "pct_dealt": 435.5,
   "pct_healed": 0.0,
   "pct_taken": 328.5,
   "resisted_hits": 2,
   "se_hits": 3,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 7,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Nasty Plot",
     5
    ],
    [
     "Make It Rain",
     5
    ],
    [
     "Protect",
     2
    ]
   ],
   "turns_active": 13,
   "types": [
    "Steel",
    "Ghost"
   ],
   "unboosts_taken": 6,
   "wins": 2
  },
  "1004": {
   "abilities": [
    [
     "Beads of Ruin",
     5
    ]
   ],
   "best": {
    "kos": 2,
    "nick": "Chip",
    "pct_dealt": 200.0,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612876698"
   },
   "boosts": 0,
   "by_player": {
    "2": 5
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 9,
   "dmg_dealt": 1886,
   "dmg_taken": 978,
   "fainted": 4,
   "form": "Chi-Yu",
   "forms": [
    [
     "Chi-Yu",
     5
    ]
   ],
   "games": 5,
   "healed": 40,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 4,
   "maxhps": [
    [
     252,
     3
    ],
    [
     130,
     2
    ]
   ],
   "mega": 0,
   "misses": 2,
   "moves_used": 9,
   "name": "Chi-Yu",
   "nicknames": [
    [
     "Chip",
     5
    ]
   ],
   "pct_dealt": 648.4,
   "pct_healed": 30.8,
   "pct_taken": 499.8,
   "resisted_hits": 2,
   "se_hits": 2,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 0,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 5,
   "top_moves": [
    [
     "Heat Wave",
     5
    ],
    [
     "Dark Pulse",
     3
    ],
    [
     "Snarl",
     1
    ]
   ],
   "turns_active": 14,
   "types": [
    "Dark",
    "Fire"
   ],
   "unboosts_taken": 2,
   "wins": 2
  },
  "1017": {
   "abilities": [],
   "best": {
    "kos": 2,
    "nick": "Hot Shrek",
    "pct_dealt": 200.0,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657512891"
   },
   "boosts": 0,
   "by_player": {
    "1": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 6,
   "dmg_dealt": 422,
   "dmg_taken": 314,
   "fainted": 2,
   "form": "Ogerpon-Cornerstone",
   "forms": [
    [
     "Ogerpon-Cornerstone",
     2
    ]
   ],
   "games": 2,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 2,
   "maxhps": [
    [
     157,
     2
    ]
   ],
   "mega": 0,
   "misses": 2,
   "moves_used": 7,
   "name": "Ogerpon",
   "nicknames": [
    [
     "Hot Shrek",
     2
    ]
   ],
   "pct_dealt": 270.9,
   "pct_healed": 0.0,
   "pct_taken": 200.0,
   "resisted_hits": 0,
   "se_hits": 2,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 1,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 2,
   "top_moves": [
    [
     "Ivy Cudgel",
     6
    ],
    [
     "Spiky Shield",
     1
    ]
   ],
   "turns_active": 8,
   "types": [
    "Grass",
    "Rock"
   ],
   "unboosts_taken": 0,
   "wins": 0
  },
  "149": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Dragonite",
    "pct_dealt": 106.8,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612894842"
   },
   "boosts": 4,
   "by_player": {
    "3": 4
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 6,
   "dmg_dealt": 517,
   "dmg_taken": 1292,
   "fainted": 4,
   "form": "Dragonite",
   "forms": [
    [
     "Dragonite",
     4
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     323,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 12,
   "name": "Dragonite",
   "nicknames": [
    [
     "Dragonite",
     4
    ]
   ],
   "pct_dealt": 146.6,
   "pct_healed": 0.0,
   "pct_taken": 400.0,
   "resisted_hits": 1,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 6,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 6,
   "top_moves": [
    [
     "Protect",
     4
    ],
    [
     "Extreme Speed",
     4
    ],
    [
     "Dragon Dance",
     2
    ],
    [
     "Outrage",
     2
    ]
   ],
   "turns_active": 15,
   "types": [
    "Dragon",
    "Flying"
   ],
   "unboosts_taken": 1,
   "wins": 3
  },
  "151": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Mew",
    "pct_dealt": 134.6,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612888680"
   },
   "boosts": 0,
   "by_player": {
    "5": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 9,
   "dmg_dealt": 711,
   "dmg_taken": 1261,
   "fainted": 3,
   "form": "Mew",
   "forms": [
    [
     "Mew",
     3
    ]
   ],
   "games": 3,
   "healed": 238,
   "immune": 0,
   "items": [
    [
     "Expert Belt",
     1
    ]
   ],
   "items_lost": 1,
   "kos": 2,
   "maxhps": [
    [
     341,
     3
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 17,
   "name": "Mew",
   "nicknames": [
    [
     "Mew",
     3
    ]
   ],
   "pct_dealt": 229.6,
   "pct_healed": 69.8,
   "pct_taken": 369.8,
   "resisted_hits": 1,
   "se_hits": 3,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 8,
   "switched_out": 3,
   "tera": 0,
   "times_sent_out": 6,
   "top_moves": [
    [
     "Draining Kiss",
     6
    ],
    [
     "Tailwind",
     5
    ],
    [
     "Psychic",
     3
    ],
    [
     "Pollen Puff",
     3
    ]
   ],
   "turns_active": 22,
   "types": [
    "Psychic"
   ],
   "unboosts_taken": 3,
   "wins": 1
  },
  "233": {
   "abilities": [
    [
     "Download",
     7
    ]
   ],
   "best": {
    "kos": 1,
    "nick": "Porygon2",
    "pct_dealt": 174.5,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612909984"
   },
   "boosts": 7,
   "by_player": {
    "3": 4
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 1,
   "damaging_moves_used": 11,
   "dmg_dealt": 1345,
   "dmg_taken": 1670,
   "fainted": 3,
   "form": "Porygon2",
   "forms": [
    [
     "Porygon2",
     4
    ]
   ],
   "games": 4,
   "healed": 374,
   "immune": 0,
   "items": [
    [
     "Eviolite",
     1
    ]
   ],
   "items_lost": 1,
   "kos": 3,
   "maxhps": [
    [
     374,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 17,
   "name": "Porygon2",
   "nicknames": [
    [
     "Porygon2",
     4
    ]
   ],
   "pct_dealt": 426.0,
   "pct_healed": 100.0,
   "pct_taken": 446.5,
   "resisted_hits": 0,
   "se_hits": 5,
   "statuses_inflicted": 1,
   "statuses_taken": 0,
   "support_moves_used": 6,
   "switched_out": 3,
   "tera": 0,
   "times_sent_out": 7,
   "top_moves": [
    [
     "Thunderbolt",
     10
    ],
    [
     "Trick Room",
     4
    ],
    [
     "Recover",
     2
    ],
    [
     "Ice Beam",
     1
    ]
   ],
   "turns_active": 26,
   "types": [
    "Normal"
   ],
   "unboosts_taken": 9,
   "wins": 3
  },
  "244": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Entei",
    "pct_dealt": 241.5,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657517850"
   },
   "boosts": 0,
   "by_player": {
    "0": 1
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 3,
   "dmg_dealt": 392,
   "dmg_taken": 157,
   "fainted": 0,
   "form": "Entei",
   "forms": [
    [
     "Entei",
     1
    ]
   ],
   "games": 1,
   "healed": 28,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     192,
     1
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 4,
   "name": "Entei",
   "nicknames": [
    [
     "Entei",
     1
    ]
   ],
   "pct_dealt": 241.5,
   "pct_healed": 14.6,
   "pct_taken": 81.8,
   "resisted_hits": 1,
   "se_hits": 1,
   "statuses_inflicted": 1,
   "statuses_taken": 0,
   "support_moves_used": 1,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 1,
   "top_moves": [
    [
     "Sacred Fire",
     3
    ],
    [
     "Protect",
     1
    ]
   ],
   "turns_active": 5,
   "types": [
    "Fire"
   ],
   "unboosts_taken": 1,
   "wins": 1
  },
  "248": {
   "abilities": [
    [
     "Unnerve",
     5
    ]
   ],
   "best": {
    "kos": 3,
    "nick": "Tyranitar",
    "pct_dealt": 386.6,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612888680"
   },
   "boosts": 0,
   "by_player": {
    "5": 3
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 2,
   "damaging_moves_used": 19,
   "dmg_dealt": 2454,
   "dmg_taken": 1463,
   "fainted": 3,
   "form": "Tyranitar",
   "forms": [
    [
     "Tyranitar",
     3
    ]
   ],
   "games": 3,
   "healed": 440,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 5,
   "maxhps": [
    [
     341,
     3
    ]
   ],
   "mega": 0,
   "misses": 3,
   "moves_used": 19,
   "name": "Tyranitar",
   "nicknames": [
    [
     "Tyranitar",
     3
    ]
   ],
   "pct_dealt": 711.7,
   "pct_healed": 129.0,
   "pct_taken": 429.0,
   "resisted_hits": 6,
   "se_hits": 5,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 0,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 5,
   "top_moves": [
    [
     "Rock Slide",
     19
    ]
   ],
   "turns_active": 27,
   "types": [
    "Rock",
    "Dark"
   ],
   "unboosts_taken": 3,
   "wins": 1
  },
  "279": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Pelipper",
    "pct_dealt": 85.0,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612881760"
   },
   "boosts": 0,
   "by_player": {
    "4": 4
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 4,
   "dmg_dealt": 425,
   "dmg_taken": 1044,
   "fainted": 4,
   "form": "Pelipper",
   "forms": [
    [
     "Pelipper",
     4
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     261,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 7,
   "name": "Pelipper",
   "nicknames": [
    [
     "Pelipper",
     4
    ]
   ],
   "pct_dealt": 124.6,
   "pct_healed": 0.0,
   "pct_taken": 400.0,
   "resisted_hits": 1,
   "se_hits": 4,
   "statuses_inflicted": 0,
   "statuses_taken": 2,
   "support_moves_used": 3,
   "switched_out": 3,
   "tera": 0,
   "times_sent_out": 7,
   "top_moves": [
    [
     "Icy Wind",
     4
    ],
    [
     "Tailwind",
     3
    ]
   ],
   "turns_active": 11,
   "types": [
    "Water",
    "Flying"
   ],
   "unboosts_taken": 0,
   "wins": 2
  },
  "3": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Vinny",
    "pct_dealt": 118.3,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657517850"
   },
   "boosts": 0,
   "by_player": {
    "2": 4
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 5,
   "dmg_dealt": 365,
   "dmg_taken": 976,
   "fainted": 4,
   "form": "Venusaur-Mega",
   "forms": [
    [
     "Venusaur-Mega",
     2
    ],
    [
     "Venusaur",
     2
    ]
   ],
   "games": 4,
   "healed": 64,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 2,
   "maxhps": [
    [
     155,
     2
    ],
    [
     301,
     2
    ]
   ],
   "mega": 4,
   "misses": 2,
   "moves_used": 10,
   "name": "Venusaur",
   "nicknames": [
    [
     "Vinny",
     4
    ]
   ],
   "pct_dealt": 176.3,
   "pct_healed": 21.3,
   "pct_taken": 421.3,
   "resisted_hits": 1,
   "se_hits": 2,
   "statuses_inflicted": 1,
   "statuses_taken": 0,
   "support_moves_used": 5,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Leech Seed",
     4
    ],
    [
     "Weather Ball",
     3
    ],
    [
     "Earth Power",
     2
    ],
    [
     "Toxic",
     1
    ]
   ],
   "turns_active": 15,
   "types": [
    "Grass",
    "Poison"
   ],
   "unboosts_taken": 5,
   "wins": 1
  },
  "373": {
   "abilities": [
    [
     "Intimidate",
     3
    ]
   ],
   "best": {
    "kos": 1,
    "nick": "Mancy",
    "pct_dealt": 183.7,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657512891"
   },
   "boosts": 0,
   "by_player": {
    "1": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 6,
   "dmg_dealt": 593,
   "dmg_taken": 340,
   "fainted": 2,
   "form": "Salamence-Mega",
   "forms": [
    [
     "Salamence-Mega",
     2
    ]
   ],
   "games": 2,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     170,
     2
    ]
   ],
   "mega": 2,
   "misses": 0,
   "moves_used": 6,
   "name": "Salamence",
   "nicknames": [
    [
     "Mancy",
     2
    ]
   ],
   "pct_dealt": 374.2,
   "pct_healed": 0.0,
   "pct_taken": 200.0,
   "resisted_hits": 2,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 0,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 3,
   "top_moves": [
    [
     "Return",
     4
    ],
    [
     "Hyper Voice",
     2
    ]
   ],
   "turns_active": 8,
   "types": [
    "Dragon",
    "Flying"
   ],
   "unboosts_taken": 2,
   "wins": 0
  },
  "38": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Prince Ember",
    "pct_dealt": 124.9,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612888680"
   },
   "boosts": 10,
   "by_player": {
    "2": 5
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 1,
   "damaging_moves_used": 2,
   "dmg_dealt": 413,
   "dmg_taken": 1082,
   "fainted": 4,
   "form": "Ninetales",
   "forms": [
    [
     "Ninetales",
     5
    ]
   ],
   "games": 5,
   "healed": 22,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     350,
     3
    ],
    [
     180,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 10,
   "name": "Ninetales",
   "nicknames": [
    [
     "Prince Ember",
     5
    ]
   ],
   "pct_dealt": 124.9,
   "pct_healed": 12.2,
   "pct_taken": 412.2,
   "resisted_hits": 0,
   "se_hits": 2,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 8,
   "switched_out": 4,
   "tera": 0,
   "times_sent_out": 8,
   "top_moves": [
    [
     "Calm Mind",
     5
    ],
    [
     "Helping Hand",
     2
    ],
    [
     "Encore",
     1
    ],
    [
     "Solar Beam",
     1
    ],
    [
     "Flamethrower",
     1
    ]
   ],
   "turns_active": 20,
   "types": [
    "Fire"
   ],
   "unboosts_taken": 7,
   "wins": 2
  },
  "547": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Whimsicott",
    "pct_dealt": 7.2,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612845958"
   },
   "boosts": 0,
   "by_player": {
    "5": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 1,
   "dmg_dealt": 27,
   "dmg_taken": 1032,
   "fainted": 3,
   "form": "Whimsicott",
   "forms": [
    [
     "Whimsicott",
     3
    ]
   ],
   "games": 3,
   "healed": 60,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     324,
     3
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 12,
   "name": "Whimsicott",
   "nicknames": [
    [
     "Whimsicott",
     3
    ]
   ],
   "pct_dealt": 7.2,
   "pct_healed": 18.5,
   "pct_taken": 318.5,
   "resisted_hits": 0,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 11,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 5,
   "top_moves": [
    [
     "Tailwind",
     5
    ],
    [
     "Light Screen",
     3
    ],
    [
     "Encore",
     3
    ],
    [
     "U-turn",
     1
    ]
   ],
   "turns_active": 13,
   "types": [
    "Grass",
    "Fairy"
   ],
   "unboosts_taken": 2,
   "wins": 1
  },
  "576": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Gothitelle",
    "pct_dealt": 128.0,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657517850"
   },
   "boosts": 0,
   "by_player": {
    "0": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 1,
   "damaging_moves_used": 5,
   "dmg_dealt": 208,
   "dmg_taken": 243,
   "fainted": 1,
   "form": "Gothitelle",
   "forms": [
    [
     "Gothitelle",
     2
    ]
   ],
   "games": 2,
   "healed": 66,
   "immune": 0,
   "items": [
    [
     "Sitrus Berry",
     1
    ]
   ],
   "items_lost": 1,
   "kos": 1,
   "maxhps": [
    [
     177,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 8,
   "name": "Gothitelle",
   "nicknames": [
    [
     "Gothitelle",
     2
    ]
   ],
   "pct_dealt": 130.4,
   "pct_healed": 37.3,
   "pct_taken": 137.3,
   "resisted_hits": 0,
   "se_hits": 2,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 3,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 2,
   "top_moves": [
    [
     "Psychic Noise",
     3
    ],
    [
     "Fake Out",
     2
    ],
    [
     "Heal Pulse",
     2
    ],
    [
     "Protect",
     1
    ]
   ],
   "turns_active": 10,
   "types": [
    "Psychic"
   ],
   "unboosts_taken": 2,
   "wins": 2
  },
  "6": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Charizard",
    "pct_dealt": 66.3,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612876698"
   },
   "boosts": 0,
   "by_player": {
    "3": 4
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 1,
   "damaging_moves_used": 5,
   "dmg_dealt": 684,
   "dmg_taken": 894,
   "fainted": 3,
   "form": "Charizard",
   "forms": [
    [
     "Charizard",
     3
    ],
    [
     "Charizard-Mega-Y",
     1
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     298,
     4
    ]
   ],
   "mega": 4,
   "misses": 0,
   "moves_used": 7,
   "name": "Charizard",
   "nicknames": [
    [
     "Charizard",
     4
    ]
   ],
   "pct_dealt": 201.5,
   "pct_healed": 0.0,
   "pct_taken": 300.0,
   "resisted_hits": 1,
   "se_hits": 1,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 2,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Protect",
     2
    ],
    [
     "Heat Wave",
     2
    ],
    [
     "Solar Beam",
     2
    ],
    [
     "Air Slash",
     1
    ]
   ],
   "turns_active": 10,
   "types": [
    "Fire",
    "Flying"
   ],
   "unboosts_taken": 2,
   "wins": 3
  },
  "645": {
   "abilities": [
    [
     "Intimidate",
     4
    ]
   ],
   "best": {
    "kos": 5,
    "nick": "Landorus",
    "pct_dealt": 276.4,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612845958"
   },
   "boosts": 0,
   "by_player": {
    "3": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 9,
   "dmg_dealt": 1698,
   "dmg_taken": 632,
   "fainted": 1,
   "form": "Landorus-Therian",
   "forms": [
    [
     "Landorus-Therian",
     3
    ]
   ],
   "games": 3,
   "healed": 0,
   "immune": 2,
   "items": [],
   "items_lost": 0,
   "kos": 6,
   "maxhps": [
    [
     382,
     3
    ]
   ],
   "mega": 0,
   "misses": 1,
   "moves_used": 9,
   "name": "Landorus",
   "nicknames": [
    [
     "Landorus",
     3
    ]
   ],
   "pct_dealt": 479.5,
   "pct_healed": 0.0,
   "pct_taken": 165.4,
   "resisted_hits": 0,
   "se_hits": 8,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 0,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Earthquake",
     7
    ],
    [
     "U-turn",
     1
    ],
    [
     "Rock Slide",
     1
    ]
   ],
   "turns_active": 10,
   "types": [
    "Ground",
    "Flying"
   ],
   "unboosts_taken": 0,
   "wins": 2
  },
  "649": {
   "abilities": [
    [
     "Download",
     2
    ]
   ],
   "best": {
    "kos": 1,
    "nick": "Genesect",
    "pct_dealt": 64.6,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657517850"
   },
   "boosts": 2,
   "by_player": {
    "0": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 2,
   "dmg_dealt": 112,
   "dmg_taken": 0,
   "fainted": 0,
   "form": "Genesect",
   "forms": [
    [
     "Genesect",
     2
    ]
   ],
   "games": 2,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     146,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 2,
   "name": "Genesect",
   "nicknames": [
    [
     "Genesect",
     2
    ]
   ],
   "pct_dealt": 82.4,
   "pct_healed": 0.0,
   "pct_taken": 0.0,
   "resisted_hits": 0,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 0,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 2,
   "top_moves": [
    [
     "Ice Beam",
     1
    ],
    [
     "U-turn",
     1
    ]
   ],
   "turns_active": 3,
   "types": [
    "Bug",
    "Steel"
   ],
   "unboosts_taken": 1,
   "wins": 2
  },
  "670": {
   "abilities": [
    [
     "Fairy Aura",
     3
    ]
   ],
   "best": {
    "kos": 1,
    "nick": "Floette",
    "pct_dealt": 113.3,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612881760"
   },
   "boosts": 2,
   "by_player": {
    "5": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 3,
   "dmg_dealt": 443,
   "dmg_taken": 578,
   "fainted": 2,
   "form": "Floette-Eternal",
   "forms": [
    [
     "Floette-Eternal",
     2
    ],
    [
     "Floette-Mega",
     1
    ]
   ],
   "games": 3,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     289,
     3
    ]
   ],
   "mega": 3,
   "misses": 0,
   "moves_used": 4,
   "name": "Floette",
   "nicknames": [
    [
     "Floette",
     3
    ]
   ],
   "pct_dealt": 129.0,
   "pct_healed": 0.0,
   "pct_taken": 200.0,
   "resisted_hits": 1,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 1,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 3,
   "top_moves": [
    [
     "Dazzling Gleam",
     2
    ],
    [
     "Calm Mind",
     1
    ],
    [
     "Moonblast",
     1
    ]
   ],
   "turns_active": 6,
   "types": [
    "Fairy"
   ],
   "unboosts_taken": 0,
   "wins": 1
  },
  "718": {
   "abilities": [
    [
     "Aura Break",
     4
    ]
   ],
   "best": {
    "kos": 3,
    "nick": "Zygarde",
    "pct_dealt": 312.4,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657505591"
   },
   "boosts": 2,
   "by_player": {
    "0": 2
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 6,
   "dmg_dealt": 732,
   "dmg_taken": 265,
   "fainted": 0,
   "form": "Zygarde",
   "forms": [
    [
     "Zygarde",
     2
    ]
   ],
   "games": 2,
   "healed": 84,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 4,
   "maxhps": [
    [
     199,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 7,
   "name": "Zygarde",
   "nicknames": [
    [
     "Zygarde",
     2
    ]
   ],
   "pct_dealt": 388.7,
   "pct_healed": 42.2,
   "pct_taken": 133.2,
   "resisted_hits": 0,
   "se_hits": 4,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 1,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Thousand Arrows",
     6
    ],
    [
     "Dragon Dance",
     1
    ]
   ],
   "turns_active": 10,
   "types": [
    "Dragon",
    "Ground"
   ],
   "unboosts_taken": 3,
   "wins": 2
  },
  "719": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Poca Roca",
    "pct_dealt": 61.7,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657505591"
   },
   "boosts": 6,
   "by_player": {
    "1": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 3,
   "dmg_dealt": 136,
   "dmg_taken": 323,
   "fainted": 2,
   "form": "Diancie",
   "forms": [
    [
     "Diancie",
     2
    ]
   ],
   "games": 2,
   "healed": 9,
   "immune": 0,
   "items": [
    [
     "Weakness Policy",
     1
    ]
   ],
   "items_lost": 1,
   "kos": 0,
   "maxhps": [
    [
     157,
     2
    ]
   ],
   "mega": 0,
   "misses": 1,
   "moves_used": 4,
   "name": "Diancie",
   "nicknames": [
    [
     "Poca Roca",
     2
    ]
   ],
   "pct_dealt": 74.6,
   "pct_healed": 5.7,
   "pct_taken": 205.7,
   "resisted_hits": 1,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 1,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Diamond Storm",
     2
    ],
    [
     "Trick Room",
     1
    ],
    [
     "Moonblast",
     1
    ]
   ],
   "turns_active": 7,
   "types": [
    "Rock",
    "Fairy"
   ],
   "unboosts_taken": 0,
   "wins": 0
  },
  "721": {
   "abilities": [],
   "best": {
    "kos": 2,
    "nick": "Tubular",
    "pct_dealt": 131.2,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657512891"
   },
   "boosts": 0,
   "by_player": {
    "1": 2
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 9,
   "dmg_dealt": 537,
   "dmg_taken": 374,
   "fainted": 2,
   "form": "Volcanion",
   "forms": [
    [
     "Volcanion",
     2
    ]
   ],
   "games": 2,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 3,
   "maxhps": [
    [
     187,
     2
    ]
   ],
   "mega": 0,
   "misses": 2,
   "moves_used": 9,
   "name": "Volcanion",
   "nicknames": [
    [
     "Tubular",
     2
    ]
   ],
   "pct_dealt": 314.9,
   "pct_healed": 0.0,
   "pct_taken": 200.0,
   "resisted_hits": 1,
   "se_hits": 3,
   "statuses_inflicted": 2,
   "statuses_taken": 0,
   "support_moves_used": 0,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Heat Wave",
     6
    ],
    [
     "Steam Eruption",
     3
    ]
   ],
   "turns_active": 12,
   "types": [
    "Fire",
    "Water"
   ],
   "unboosts_taken": 2,
   "wins": 0
  },
  "727": {
   "abilities": [
    [
     "Intimidate",
     13
    ]
   ],
   "best": {
    "kos": 1,
    "nick": "Incineroar",
    "pct_dealt": 64.6,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612894842"
   },
   "boosts": 0,
   "by_player": {
    "4": 4
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 2,
   "damaging_moves_used": 16,
   "dmg_dealt": 773,
   "dmg_taken": 1146,
   "fainted": 3,
   "form": "Incineroar",
   "forms": [
    [
     "Incineroar",
     4
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     382,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 23,
   "name": "Incineroar",
   "nicknames": [
    [
     "Incineroar",
     4
    ]
   ],
   "pct_dealt": 225.4,
   "pct_healed": 0.0,
   "pct_taken": 300.0,
   "resisted_hits": 5,
   "se_hits": 1,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 7,
   "switched_out": 10,
   "tera": 0,
   "times_sent_out": 13,
   "top_moves": [
    [
     "Fake Out",
     12
    ],
    [
     "Parting Shot",
     6
    ],
    [
     "Knock Off",
     4
    ],
    [
     "Flare Blitz",
     1
    ]
   ],
   "turns_active": 30,
   "types": [
    "Fire",
    "Dark"
   ],
   "unboosts_taken": 1,
   "wins": 2
  },
  "764": {
   "abilities": [],
   "best": {
    "kos": 3,
    "nick": "Comfey",
    "pct_dealt": 271.2,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657505591"
   },
   "boosts": 4,
   "by_player": {
    "0": 1
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 7,
   "dmg_dealt": 482,
   "dmg_taken": 530,
   "fainted": 0,
   "form": "Comfey",
   "forms": [
    [
     "Comfey",
     1
    ]
   ],
   "games": 1,
   "healed": 483,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 3,
   "maxhps": [
    [
     158,
     1
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 13,
   "name": "Comfey",
   "nicknames": [
    [
     "Comfey",
     1
    ]
   ],
   "pct_dealt": 271.2,
   "pct_healed": 305.7,
   "pct_taken": 335.4,
   "resisted_hits": 0,
   "se_hits": 3,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 6,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 1,
   "top_moves": [
    [
     "Draining Kiss",
     7
    ],
    [
     "Leech Seed",
     4
    ],
    [
     "Calm Mind",
     2
    ]
   ],
   "turns_active": 13,
   "types": [
    "Fairy"
   ],
   "unboosts_taken": 3,
   "wins": 1
  },
  "788": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Ursula",
    "pct_dealt": 40.2,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612888680"
   },
   "boosts": 6,
   "by_player": {
    "2": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 2,
   "damaging_moves_used": 3,
   "dmg_dealt": 223,
   "dmg_taken": 1344,
   "fainted": 3,
   "form": "Tapu Fini",
   "forms": [
    [
     "Tapu Fini",
     3
    ]
   ],
   "games": 3,
   "healed": 312,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     344,
     3
    ]
   ],
   "mega": 0,
   "misses": 1,
   "moves_used": 8,
   "name": "Tapu Fini",
   "nicknames": [
    [
     "Ursula",
     3
    ]
   ],
   "pct_dealt": 70.6,
   "pct_healed": 90.7,
   "pct_taken": 390.7,
   "resisted_hits": 1,
   "se_hits": 1,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 5,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 3,
   "top_moves": [
    [
     "Calm Mind",
     3
    ],
    [
     "Icy Wind",
     2
    ],
    [
     "Soak",
     2
    ],
    [
     "Draining Kiss",
     1
    ]
   ],
   "turns_active": 13,
   "types": [
    "Water",
    "Fairy"
   ],
   "unboosts_taken": 0,
   "wins": 1
  },
  "801": {
   "abilities": [
    [
     "Soul-Heart",
     16
    ]
   ],
   "best": {
    "kos": 4,
    "nick": "Mags",
    "pct_dealt": 192.7,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657512891"
   },
   "boosts": 26,
   "by_player": {
    "2": 5
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 12,
   "dmg_dealt": 3126,
   "dmg_taken": 1169,
   "fainted": 3,
   "form": "Magearna",
   "forms": [
    [
     "Magearna",
     5
    ]
   ],
   "games": 5,
   "healed": 44,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 10,
   "maxhps": [
    [
     364,
     3
    ],
    [
     187,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 25,
   "name": "Magearna",
   "nicknames": [
    [
     "Mags",
     5
    ]
   ],
   "pct_dealt": 992.3,
   "pct_healed": 23.5,
   "pct_taken": 392.1,
   "resisted_hits": 4,
   "se_hits": 8,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 13,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 5,
   "top_moves": [
    [
     "Dazzling Gleam",
     9
    ],
    [
     "Protect",
     8
    ],
    [
     "Calm Mind",
     5
    ],
    [
     "Energy Ball",
     2
    ],
    [
     "Shadow Ball",
     1
    ]
   ],
   "turns_active": 28,
   "types": [
    "Steel",
    "Fairy"
   ],
   "unboosts_taken": 0,
   "wins": 2
  },
  "809": {
   "abilities": [],
   "best": {
    "kos": 2,
    "nick": "Melmetal",
    "pct_dealt": 140.4,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612845958"
   },
   "boosts": 0,
   "by_player": {
    "5": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 10,
   "dmg_dealt": 1582,
   "dmg_taken": 1174,
   "fainted": 2,
   "form": "Melmetal",
   "forms": [
    [
     "Melmetal",
     3
    ]
   ],
   "games": 3,
   "healed": 0,
   "immune": 1,
   "items": [],
   "items_lost": 0,
   "kos": 5,
   "maxhps": [
    [
     474,
     3
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 12,
   "name": "Melmetal",
   "nicknames": [
    [
     "Melmetal",
     3
    ]
   ],
   "pct_dealt": 469.1,
   "pct_healed": 0.0,
   "pct_taken": 247.7,
   "resisted_hits": 2,
   "se_hits": 6,
   "statuses_inflicted": 1,
   "statuses_taken": 0,
   "support_moves_used": 2,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 3,
   "top_moves": [
    [
     "Superpower",
     7
    ],
    [
     "Double Iron Bash",
     3
    ],
    [
     "Toxic",
     1
    ],
    [
     "Protect",
     1
    ]
   ],
   "turns_active": 15,
   "types": [
    "Steel"
   ],
   "unboosts_taken": 14,
   "wins": 1
  },
  "812": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Rillaboom",
    "pct_dealt": 72.7,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657517850"
   },
   "boosts": 0,
   "by_player": {
    "0": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 5,
   "dmg_dealt": 118,
   "dmg_taken": 316,
   "fainted": 1,
   "form": "Rillaboom",
   "forms": [
    [
     "Rillaboom",
     2
    ]
   ],
   "games": 2,
   "healed": 72,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 1,
   "maxhps": [
    [
     207,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 5,
   "name": "Rillaboom",
   "nicknames": [
    [
     "Rillaboom",
     2
    ]
   ],
   "pct_dealt": 80.6,
   "pct_healed": 34.8,
   "pct_taken": 152.7,
   "resisted_hits": 1,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 0,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 3,
   "top_moves": [
    [
     "Fake Out",
     3
    ],
    [
     "Grassy Glide",
     2
    ]
   ],
   "turns_active": 7,
   "types": [
    "Grass"
   ],
   "unboosts_taken": 2,
   "wins": 2
  },
  "861": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "It's not a phase!",
    "pct_dealt": 0.0,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657505591"
   },
   "boosts": 0,
   "by_player": {
    "1": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 0,
   "dmg_dealt": 0,
   "dmg_taken": 416,
   "fainted": 2,
   "form": "Grimmsnarl",
   "forms": [
    [
     "Grimmsnarl",
     2
    ]
   ],
   "games": 2,
   "healed": 12,
   "immune": 1,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     202,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 11,
   "name": "Grimmsnarl",
   "nicknames": [
    [
     "It's not a phase!",
     2
    ]
   ],
   "pct_dealt": 0.0,
   "pct_healed": 5.9,
   "pct_taken": 205.9,
   "resisted_hits": 0,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 11,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Scary Face",
     4
    ],
    [
     "Parting Shot",
     3
    ],
    [
     "Reflect",
     2
    ],
    [
     "Light Screen",
     2
    ]
   ],
   "turns_active": 13,
   "types": [
    "Dark",
    "Fairy"
   ],
   "unboosts_taken": 2,
   "wins": 0
  },
  "887": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Dragapult",
    "pct_dealt": 104.7,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612881760"
   },
   "boosts": 0,
   "by_player": {
    "5": 3
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 5,
   "dmg_dealt": 446,
   "dmg_taken": 951,
   "fainted": 3,
   "form": "Dragapult",
   "forms": [
    [
     "Dragapult",
     3
    ]
   ],
   "games": 3,
   "healed": 0,
   "immune": 0,
   "items": [
    [
     "Focus Sash",
     1
    ]
   ],
   "items_lost": 1,
   "kos": 0,
   "maxhps": [
    [
     317,
     3
    ]
   ],
   "mega": 0,
   "misses": 1,
   "moves_used": 8,
   "name": "Dragapult",
   "nicknames": [
    [
     "Dragapult",
     3
    ]
   ],
   "pct_dealt": 138.7,
   "pct_healed": 0.0,
   "pct_taken": 300.0,
   "resisted_hits": 1,
   "se_hits": 0,
   "statuses_inflicted": 2,
   "statuses_taken": 0,
   "support_moves_used": 3,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Draco Meteor",
     3
    ],
    [
     "Thunder Wave",
     2
    ],
    [
     "Hex",
     2
    ],
    [
     "Will-O-Wisp",
     1
    ]
   ],
   "turns_active": 9,
   "types": [
    "Dragon",
    "Ghost"
   ],
   "unboosts_taken": 11,
   "wins": 1
  },
  "9": {
   "abilities": [],
   "best": {
    "kos": 2,
    "nick": "Blastoise",
    "pct_dealt": 105.3,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612894842"
   },
   "boosts": 0,
   "by_player": {
    "4": 4
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 15,
   "dmg_dealt": 1935,
   "dmg_taken": 1940,
   "fainted": 2,
   "form": "Blastoise",
   "forms": [
    [
     "Blastoise",
     4
    ]
   ],
   "games": 4,
   "healed": 901,
   "immune": 1,
   "items": [],
   "items_lost": 0,
   "kos": 4,
   "maxhps": [
    [
     362,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 23,
   "name": "Blastoise",
   "nicknames": [
    [
     "Blastoise",
     4
    ]
   ],
   "pct_dealt": 566.0,
   "pct_healed": 248.9,
   "pct_taken": 535.9,
   "resisted_hits": 8,
   "se_hits": 7,
   "statuses_inflicted": 0,
   "statuses_taken": 2,
   "support_moves_used": 8,
   "switched_out": 5,
   "tera": 0,
   "times_sent_out": 8,
   "top_moves": [
    [
     "Water Spout",
     10
    ],
    [
     "Fake Out",
     5
    ],
    [
     "Protect",
     5
    ],
    [
     "Life Dew",
     3
    ]
   ],
   "turns_active": 31,
   "types": [
    "Water"
   ],
   "unboosts_taken": 2,
   "wins": 2
  },
  "901": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Ursa Major",
    "pct_dealt": 85.4,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657512891"
   },
   "boosts": 0,
   "by_player": {
    "2": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 4,
   "dmg_dealt": 291,
   "dmg_taken": 276,
   "fainted": 1,
   "form": "Ursaluna-Bloodmoon",
   "forms": [
    [
     "Ursaluna-Bloodmoon",
     2
    ]
   ],
   "games": 2,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     197,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 4,
   "name": "Ursaluna",
   "nicknames": [
    [
     "Ursa Major",
     2
    ]
   ],
   "pct_dealt": 139.6,
   "pct_healed": 0.0,
   "pct_taken": 140.1,
   "resisted_hits": 1,
   "se_hits": 1,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 0,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 2,
   "top_moves": [
    [
     "Snarl",
     2
    ],
    [
     "Earth Power",
     2
    ]
   ],
   "turns_active": 6,
   "types": [
    "Ground",
    "Normal"
   ],
   "unboosts_taken": 1,
   "wins": 1
  },
  "934": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Garganacl",
    "pct_dealt": 128.4,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612894842"
   },
   "boosts": 0,
   "by_player": {
    "4": 3
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 1,
   "damaging_moves_used": 9,
   "dmg_dealt": 522,
   "dmg_taken": 1403,
   "fainted": 2,
   "form": "Garganacl",
   "forms": [
    [
     "Garganacl",
     3
    ]
   ],
   "games": 3,
   "healed": 202,
   "immune": 0,
   "items": [
    [
     "Sitrus Berry",
     2
    ]
   ],
   "items_lost": 2,
   "kos": 1,
   "maxhps": [
    [
     404,
     3
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 11,
   "name": "Garganacl",
   "nicknames": [
    [
     "Garganacl",
     3
    ]
   ],
   "pct_dealt": 136.4,
   "pct_healed": 50.0,
   "pct_taken": 347.3,
   "resisted_hits": 1,
   "se_hits": 4,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 2,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 4,
   "top_moves": [
    [
     "Salt Cure",
     5
    ],
    [
     "Body Press",
     4
    ],
    [
     "Wide Guard",
     2
    ]
   ],
   "turns_active": 16,
   "types": [
    "Rock"
   ],
   "unboosts_taken": 1,
   "wins": 1
  },
  "94": {
   "abilities": [],
   "best": {
    "kos": 3,
    "nick": "Gengar",
    "pct_dealt": 343.3,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612867531"
   },
   "boosts": 0,
   "by_player": {
    "4": 4
   },
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 0,
   "damaging_moves_used": 8,
   "dmg_dealt": 1195,
   "dmg_taken": 1065,
   "fainted": 3,
   "form": "Gengar",
   "forms": [
    [
     "Gengar",
     3
    ],
    [
     "Gengar-Mega",
     1
    ]
   ],
   "games": 4,
   "healed": 95,
   "immune": 6,
   "items": [],
   "items_lost": 0,
   "kos": 4,
   "maxhps": [
    [
     262,
     4
    ]
   ],
   "mega": 3,
   "misses": 0,
   "moves_used": 9,
   "name": "Gengar",
   "nicknames": [
    [
     "Gengar",
     4
    ]
   ],
   "pct_dealt": 372.1,
   "pct_healed": 36.3,
   "pct_taken": 406.5,
   "resisted_hits": 0,
   "se_hits": 3,
   "statuses_inflicted": 1,
   "statuses_taken": 0,
   "support_moves_used": 1,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 5,
   "top_moves": [
    [
     "Sludge Wave",
     5
    ],
    [
     "Shadow Ball",
     3
    ],
    [
     "Protect",
     1
    ]
   ],
   "turns_active": 13,
   "types": [
    "Ghost",
    "Poison"
   ],
   "unboosts_taken": 1,
   "wins": 2
  },
  "981": {
   "abilities": [],
   "best": {
    "kos": 0,
    "nick": "Wemby",
    "pct_dealt": 0.0,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657505591"
   },
   "boosts": 0,
   "by_player": {
    "1": 2
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 1,
   "damaging_moves_used": 0,
   "dmg_dealt": 0,
   "dmg_taken": 454,
   "fainted": 2,
   "form": "Farigiraf",
   "forms": [
    [
     "Farigiraf",
     2
    ]
   ],
   "games": 2,
   "healed": 0,
   "immune": 0,
   "items": [],
   "items_lost": 0,
   "kos": 0,
   "maxhps": [
    [
     227,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 2,
   "name": "Farigiraf",
   "nicknames": [
    [
     "Wemby",
     2
    ]
   ],
   "pct_dealt": 0.0,
   "pct_healed": 0.0,
   "pct_taken": 200.0,
   "resisted_hits": 0,
   "se_hits": 0,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 2,
   "switched_out": 0,
   "tera": 0,
   "times_sent_out": 2,
   "top_moves": [
    [
     "Helping Hand",
     2
    ]
   ],
   "turns_active": 3,
   "types": [
    "Normal",
    "Psychic"
   ],
   "unboosts_taken": 2,
   "wins": 0
  },
  "983": {
   "abilities": [],
   "best": {
    "kos": 3,
    "nick": "Kingambit",
    "pct_dealt": 240.5,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612894842"
   },
   "boosts": 0,
   "by_player": {
    "3": 4
   },
   "crits_landed": 2,
   "crits_landed_luck": 2,
   "crits_taken": 0,
   "damaging_moves_used": 11,
   "dmg_dealt": 1891,
   "dmg_taken": 1291,
   "fainted": 2,
   "form": "Kingambit",
   "forms": [
    [
     "Kingambit",
     4
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 0,
   "items": [
    [
     "Black Glasses",
     1
    ]
   ],
   "items_lost": 1,
   "kos": 6,
   "maxhps": [
    [
     404,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 16,
   "name": "Kingambit",
   "nicknames": [
    [
     "Kingambit",
     4
    ]
   ],
   "pct_dealt": 564.1,
   "pct_healed": 0.0,
   "pct_taken": 319.6,
   "resisted_hits": 3,
   "se_hits": 7,
   "statuses_inflicted": 0,
   "statuses_taken": 0,
   "support_moves_used": 5,
   "switched_out": 1,
   "tera": 0,
   "times_sent_out": 5,
   "top_moves": [
    [
     "Iron Head",
     5
    ],
    [
     "Protect",
     5
    ],
    [
     "Sucker Punch",
     4
    ],
    [
     "Kowtow Cleave",
     2
    ]
   ],
   "turns_active": 19,
   "types": [
    "Dark",
    "Steel"
   ],
   "unboosts_taken": 4,
   "wins": 3
  },
  "986": {
   "abilities": [],
   "best": {
    "kos": 2,
    "nick": "Brute Bonnet",
    "pct_dealt": 212.2,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612909984"
   },
   "boosts": 0,
   "by_player": {
    "3": 4
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 9,
   "dmg_dealt": 1567,
   "dmg_taken": 1307,
   "fainted": 3,
   "form": "Brute Bonnet",
   "forms": [
    [
     "Brute Bonnet",
     4
    ]
   ],
   "games": 4,
   "healed": 0,
   "immune": 1,
   "items": [
    [
     "Booster Energy",
     3
    ]
   ],
   "items_lost": 3,
   "kos": 4,
   "maxhps": [
    [
     426,
     4
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 17,
   "name": "Brute Bonnet",
   "nicknames": [
    [
     "Brute Bonnet",
     4
    ]
   ],
   "pct_dealt": 485.4,
   "pct_healed": 0.0,
   "pct_taken": 306.8,
   "resisted_hits": 0,
   "se_hits": 6,
   "statuses_inflicted": 4,
   "statuses_taken": 0,
   "support_moves_used": 8,
   "switched_out": 4,
   "tera": 0,
   "times_sent_out": 7,
   "top_moves": [
    [
     "Seed Bomb",
     6
    ],
    [
     "Spore",
     5
    ],
    [
     "Sucker Punch",
     3
    ],
    [
     "Rage Powder",
     3
    ]
   ],
   "turns_active": 24,
   "types": [
    "Grass",
    "Dark"
   ],
   "unboosts_taken": 6,
   "wins": 3
  },
  "987": {
   "abilities": [],
   "best": {
    "kos": 1,
    "nick": "Floots",
    "pct_dealt": 48.2,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612876698"
   },
   "boosts": 0,
   "by_player": {
    "2": 5
   },
   "crits_landed": 0,
   "crits_landed_luck": 0,
   "crits_taken": 0,
   "damaging_moves_used": 8,
   "dmg_dealt": 639,
   "dmg_taken": 969,
   "fainted": 4,
   "form": "Flutter Mane",
   "forms": [
    [
     "Flutter Mane",
     5
    ]
   ],
   "games": 5,
   "healed": 8,
   "immune": 0,
   "items": [
    [
     "Focus Sash",
     2
    ]
   ],
   "items_lost": 2,
   "kos": 1,
   "maxhps": [
    [
     251,
     3
    ],
    [
     130,
     2
    ]
   ],
   "mega": 0,
   "misses": 0,
   "moves_used": 10,
   "name": "Flutter Mane",
   "nicknames": [
    [
     "Floots",
     5
    ]
   ],
   "pct_dealt": 251.7,
   "pct_healed": 6.2,
   "pct_taken": 485.4,
   "resisted_hits": 5,
   "se_hits": 3,
   "statuses_inflicted": 0,
   "statuses_taken": 1,
   "support_moves_used": 2,
   "switched_out": 2,
   "tera": 0,
   "times_sent_out": 6,
   "top_moves": [
    [
     "Icy Wind",
     5
    ],
    [
     "Protect",
     2
    ],
    [
     "Shadow Ball",
     2
    ],
    [
     "Dazzling Gleam",
     1
    ]
   ],
   "turns_active": 14,
   "types": [
    "Ghost",
    "Fairy"
   ],
   "unboosts_taken": 3,
   "wins": 2
  }
 },
 "dex_types": {
  "1000": [
   "Steel",
   "Ghost"
  ],
  "1002": [
   "Dark",
   "Ice"
  ],
  "1003": [
   "Dark",
   "Ground"
  ],
  "1004": [
   "Dark",
   "Fire"
  ],
  "1009": [
   "Water",
   "Dragon"
  ],
  "1013": [
   "Grass",
   "Ghost"
  ],
  "1017": [
   "Grass"
  ],
  "1018": [
   "Steel",
   "Dragon"
  ],
  "1021": [
   "Electric",
   "Dragon"
  ],
  "115": [
   "Normal"
  ],
  "145": [
   "Electric",
   "Flying"
  ],
  "149": [
   "Dragon",
   "Flying"
  ],
  "151": [
   "Psychic"
  ],
  "233": [
   "Normal"
  ],
  "235": [
   "Normal"
  ],
  "244": [
   "Fire"
  ],
  "248": [
   "Rock",
   "Dark"
  ],
  "279": [
   "Water",
   "Flying"
  ],
  "3": [
   "Grass",
   "Poison"
  ],
  "324": [
   "Fire"
  ],
  "373": [
   "Dragon",
   "Flying"
  ],
  "376": [
   "Steel",
   "Psychic"
  ],
  "38": [
   "Fire"
  ],
  "386": [
   "Psychic"
  ],
  "445": [
   "Dragon",
   "Ground"
  ],
  "478": [
   "Ice",
   "Ghost"
  ],
  "488": [
   "Psychic"
  ],
  "491": [
   "Dark"
  ],
  "547": [
   "Grass",
   "Fairy"
  ],
  "576": [
   "Psychic"
  ],
  "591": [
   "Grass",
   "Poison"
  ],
  "6": [
   "Fire",
   "Flying"
  ],
  "641": [
   "Flying"
  ],
  "645": [
   "Ground",
   "Flying"
  ],
  "649": [
   "Bug",
   "Steel"
  ],
  "655": [
   "Fire",
   "Psychic"
  ],
  "670": [
   "Fairy"
  ],
  "700": [
   "Fairy"
  ],
  "718": [
   "Dragon",
   "Ground"
  ],
  "719": [
   "Rock",
   "Fairy"
  ],
  "721": [
   "Fire",
   "Water"
  ],
  "727": [
   "Fire",
   "Dark"
  ],
  "764": [
   "Fairy"
  ],
  "784": [
   "Dragon",
   "Fighting"
  ],
  "786": [
   "Psychic",
   "Fairy"
  ],
  "788": [
   "Water",
   "Fairy"
  ],
  "797": [
   "Steel",
   "Flying"
  ],
  "798": [
   "Grass",
   "Steel"
  ],
  "801": [
   "Steel",
   "Fairy"
  ],
  "802": [
   "Fighting",
   "Ghost"
  ],
  "807": [
   "Electric"
  ],
  "809": [
   "Steel"
  ],
  "812": [
   "Grass"
  ],
  "861": [
   "Dark",
   "Fairy"
  ],
  "876": [
   "Psychic",
   "Normal"
  ],
  "887": [
   "Dragon",
   "Ghost"
  ],
  "892": [
   "Fighting",
   "Dark"
  ],
  "895": [
   "Dragon"
  ],
  "9": [
   "Water"
  ],
  "901": [
   "Ground",
   "Normal"
  ],
  "902": [
   "Water",
   "Ghost"
  ],
  "934": [
   "Rock"
  ],
  "94": [
   "Ghost",
   "Poison"
  ],
  "979": [
   "Fighting",
   "Ghost"
  ],
  "981": [
   "Normal",
   "Psychic"
  ],
  "983": [
   "Dark",
   "Steel"
  ],
  "984": [
   "Ground",
   "Fighting"
  ],
  "986": [
   "Grass",
   "Dark"
  ],
  "987": [
   "Ghost",
   "Fairy"
  ],
  "991": [
   "Ice",
   "Water"
  ],
  "992": [
   "Fighting",
   "Electric"
  ],
  "998": [
   "Dragon",
   "Ice"
  ]
 },
 "meta": {
  "archived_replays": 10,
  "battles": 10,
  "coverage_pct": 100.0,
  "linked_replays": 10,
  "recorded_matches": 10,
  "season": "s9",
  "seconds": 9129,
  "turns": 133,
  "unmapped_accounts": [],
  "unparsed_replays": [],
  "unrecorded_replays": 0
 },
 "players": {
  "0": {
   "best": {
    "kos": 6,
    "pct_dealt": 611.7,
    "turns": 14,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657505591"
   },
   "boosts": 8,
   "chat": 0,
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 1,
   "damaging_moves_used": 28,
   "dmg_dealt": 2044,
   "dmg_taken": 1511,
   "fainted": 2,
   "games": 2,
   "h2h": {
    "1": 1,
    "2": 1
   },
   "hazards": [],
   "healed": 733,
   "immune": 0,
   "items_lost": 1,
   "kos": 11,
   "mega": 0,
   "misses": 0,
   "moves_used": 39,
   "pct_dealt": 1194.8,
   "pct_healed": 434.6,
   "pct_taken": 840.3,
   "recorded_games": 2,
   "resisted_hits": 2,
   "se_hits": 10,
   "seconds": 1426,
   "statuses_inflicted": 1,
   "statuses_taken": 1,
   "support_moves_used": 11,
   "switched_out": 7,
   "switches": 7,
   "tera": 0,
   "tera_turns": [],
   "times_sent_out": 13,
   "top_moves": [
    [
     "Draining Kiss",
     7
    ],
    [
     "Thousand Arrows",
     6
    ],
    [
     "Fake Out",
     5
    ],
    [
     "Leech Seed",
     4
    ],
    [
     "Sacred Fire",
     3
    ],
    [
     "Psychic Noise",
     3
    ],
    [
     "Calm Mind",
     2
    ],
    [
     "Heal Pulse",
     2
    ]
   ],
   "turns": 24,
   "turns_active": 48,
   "unboosts_taken": 12,
   "wins": 2
  },
  "1": {
   "best": {
    "kos": 5,
    "pct_dealt": 527.7,
    "turns": 12,
    "url": "https://replay.pokemonshowdown.com/gen9championsdoublescustomgame-2657512891"
   },
   "boosts": 6,
   "chat": 0,
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 1,
   "damaging_moves_used": 24,
   "dmg_dealt": 1688,
   "dmg_taken": 2221,
   "fainted": 12,
   "games": 2,
   "h2h": {},
   "hazards": [
    [
     "Reflect",
     2
    ],
    [
     "Light Screen",
     2
    ]
   ],
   "healed": 21,
   "immune": 1,
   "items_lost": 1,
   "kos": 6,
   "mega": 2,
   "misses": 5,
   "moves_used": 39,
   "pct_dealt": 1034.6,
   "pct_healed": 11.7,
   "pct_taken": 1211.7,
   "recorded_games": 2,
   "resisted_hits": 4,
   "se_hits": 5,
   "seconds": 1515,
   "statuses_inflicted": 2,
   "statuses_taken": 1,
   "support_moves_used": 15,
   "switched_out": 7,
   "switches": 7,
   "tera": 0,
   "tera_turns": [],
   "times_sent_out": 19,
   "top_moves": [
    [
     "Heat Wave",
     6
    ],
    [
     "Ivy Cudgel",
     6
    ],
    [
     "Return",
     4
    ],
    [
     "Scary Face",
     4
    ],
    [
     "Parting Shot",
     3
    ],
    [
     "Steam Eruption",
     3
    ],
    [
     "Reflect",
     2
    ],
    [
     "Light Screen",
     2
    ]
   ],
   "turns": 26,
   "turns_active": 51,
   "unboosts_taken": 8,
   "wins": 0
  },
  "2": {
   "best": {
    "kos": 6,
    "pct_dealt": 600.0,
    "turns": 7,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612876698"
   },
   "boosts": 42,
   "chat": 5,
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 3,
   "damaging_moves_used": 43,
   "dmg_dealt": 6943,
   "dmg_taken": 6794,
   "fainted": 23,
   "games": 5,
   "h2h": {
    "1": 1,
    "3": 1
   },
   "hazards": [],
   "healed": 490,
   "immune": 0,
   "items_lost": 2,
   "kos": 17,
   "mega": 4,
   "misses": 5,
   "moves_used": 76,
   "pct_dealt": 2403.9,
   "pct_healed": 184.6,
   "pct_taken": 2741.7,
   "recorded_games": 5,
   "resisted_hits": 14,
   "se_hits": 19,
   "seconds": 3165,
   "statuses_inflicted": 1,
   "statuses_taken": 3,
   "support_moves_used": 33,
   "switched_out": 7,
   "switches": 7,
   "tera": 0,
   "tera_turns": [],
   "times_sent_out": 33,
   "top_moves": [
    [
     "Calm Mind",
     13
    ],
    [
     "Protect",
     10
    ],
    [
     "Dazzling Gleam",
     10
    ],
    [
     "Icy Wind",
     7
    ],
    [
     "Heat Wave",
     5
    ],
    [
     "Leech Seed",
     4
    ],
    [
     "Earth Power",
     4
    ],
    [
     "Weather Ball",
     3
    ]
   ],
   "turns": 58,
   "turns_active": 110,
   "unboosts_taken": 18,
   "wins": 2
  },
  "3": {
   "best": {
    "kos": 7,
    "pct_dealt": 695.4,
    "turns": 17,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612845958"
   },
   "boosts": 11,
   "chat": 19,
   "crits_landed": 3,
   "crits_landed_luck": 3,
   "crits_taken": 2,
   "damaging_moves_used": 51,
   "dmg_dealt": 7702,
   "dmg_taken": 7086,
   "fainted": 16,
   "games": 4,
   "h2h": {
    "4": 2,
    "5": 1
   },
   "hazards": [],
   "healed": 374,
   "immune": 3,
   "items_lost": 5,
   "kos": 20,
   "mega": 4,
   "misses": 1,
   "moves_used": 78,
   "pct_dealt": 2303.2,
   "pct_healed": 100.0,
   "pct_taken": 1938.3,
   "recorded_games": 4,
   "resisted_hits": 5,
   "se_hits": 27,
   "seconds": 4808,
   "statuses_inflicted": 5,
   "statuses_taken": 2,
   "support_moves_used": 27,
   "switched_out": 12,
   "switches": 12,
   "tera": 0,
   "tera_turns": [],
   "times_sent_out": 33,
   "top_moves": [
    [
     "Protect",
     11
    ],
    [
     "Thunderbolt",
     10
    ],
    [
     "Sucker Punch",
     7
    ],
    [
     "Earthquake",
     7
    ],
    [
     "Seed Bomb",
     6
    ],
    [
     "Spore",
     5
    ],
    [
     "Iron Head",
     5
    ],
    [
     "Trick Room",
     4
    ]
   ],
   "turns": 53,
   "turns_active": 104,
   "unboosts_taken": 22,
   "wins": 3
  },
  "4": {
   "best": {
    "kos": 6,
    "pct_dealt": 681.6,
    "turns": 14,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612867531"
   },
   "boosts": 10,
   "chat": 4,
   "crits_landed": 5,
   "crits_landed_luck": 5,
   "crits_taken": 3,
   "damaging_moves_used": 57,
   "dmg_dealt": 6315,
   "dmg_taken": 7636,
   "fainted": 16,
   "games": 4,
   "h2h": {
    "2": 1,
    "5": 1
   },
   "hazards": [
    [
     "Tailwind",
     3
    ]
   ],
   "healed": 1198,
   "immune": 7,
   "items_lost": 2,
   "kos": 17,
   "mega": 3,
   "misses": 0,
   "moves_used": 85,
   "pct_dealt": 1860.0,
   "pct_healed": 335.2,
   "pct_taken": 2318.2,
   "recorded_games": 4,
   "resisted_hits": 17,
   "se_hits": 22,
   "seconds": 5229,
   "statuses_inflicted": 1,
   "statuses_taken": 4,
   "support_moves_used": 28,
   "switched_out": 21,
   "switches": 21,
   "tera": 0,
   "tera_turns": [],
   "times_sent_out": 41,
   "top_moves": [
    [
     "Fake Out",
     17
    ],
    [
     "Water Spout",
     10
    ],
    [
     "Protect",
     8
    ],
    [
     "Parting Shot",
     6
    ],
    [
     "Sludge Wave",
     5
    ],
    [
     "Nasty Plot",
     5
    ],
    [
     "Make It Rain",
     5
    ],
    [
     "Salt Cure",
     5
    ]
   ],
   "turns": 58,
   "turns_active": 114,
   "unboosts_taken": 11,
   "wins": 2
  },
  "5": {
   "best": {
    "kos": 6,
    "pct_dealt": 648.1,
    "turns": 15,
    "url": "https://replay.pokemonshowdown.com/gen9doublescustomgame-2612888680"
   },
   "boosts": 2,
   "chat": 14,
   "crits_landed": 1,
   "crits_landed_luck": 1,
   "crits_taken": 2,
   "damaging_moves_used": 47,
   "dmg_dealt": 5663,
   "dmg_taken": 6459,
   "fainted": 16,
   "games": 3,
   "h2h": {
    "2": 1
   },
   "hazards": [
    [
     "Tailwind",
     9
    ],
    [
     "Light Screen",
     3
    ]
   ],
   "healed": 738,
   "immune": 1,
   "items_lost": 2,
   "kos": 13,
   "mega": 3,
   "misses": 4,
   "moves_used": 72,
   "pct_dealt": 1685.2,
   "pct_healed": 217.3,
   "pct_taken": 1865.0,
   "recorded_games": 3,
   "resisted_hits": 11,
   "se_hits": 14,
   "seconds": 2115,
   "statuses_inflicted": 3,
   "statuses_taken": 2,
   "support_moves_used": 25,
   "switched_out": 8,
   "switches": 8,
   "tera": 0,
   "tera_turns": [],
   "times_sent_out": 26,
   "top_moves": [
    [
     "Rock Slide",
     19
    ],
    [
     "Tailwind",
     10
    ],
    [
     "Superpower",
     7
    ],
    [
     "Draining Kiss",
     6
    ],
    [
     "Draco Meteor",
     3
    ],
    [
     "Light Screen",
     3
    ],
    [
     "Encore",
     3
    ],
    [
     "Double Iron Bash",
     3
    ]
   ],
   "turns": 47,
   "turns_active": 92,
   "unboosts_taken": 33,
   "wins": 1
  }
 }
};
