/**
 * Click-through battle stats panel.
 *
 * Reads `replay_stats` (generated by helper/replay_stats.py from the Pokemon Showdown
 * replay logs) and shows a detail panel when a Pokemon or trainer is clicked.
 *
 * Anything with data-dex="<national dex id>" or data-player="<pokeblunt player id>"
 * and the "stat-link" class becomes clickable.
 */

// Damage is stored as a percent-of-max-HP sum, so 5264.2 means 52.6 full HP bars.
// Normalising by max HP keeps a hit on Blissey from outweighing a hit on Chi-Yu.
function bars(pct) {
    return (pct / 100).toFixed(1);
}

function ratio(numerator, denominator) {
    if (!denominator) {
        return numerator ? "∞" : "0.00";
    }
    return (numerator / denominator).toFixed(2);
}

function per_game(value, games) {
    return games ? (value / games).toFixed(2) : "0.00";
}

function percent(numerator, denominator) {
    return denominator ? Math.round((100 * numerator) / denominator) + "%" : "–";
}

function clock(seconds) {
    var minutes = Math.floor(seconds / 60);
    return minutes + "m" + String(Math.round(seconds % 60)).padStart(2, "0") + "s";
}

function mean(numbers) {
    if (!numbers.length) {
        return 0;
    }
    return numbers.reduce(function (a, b) { return a + b; }, 0) / numbers.length;
}

/** Serebii pads dex numbers to 3 digits, or 4 once past #999. */
function dex_pad(dex) {
    return String(dex).padStart(Number(dex) >= 1000 ? 4 : 3, "0");
}

function sprite_url(dex) {
    return "https://www.serebii.net/pokedex-sv/icon/" + dex_pad(dex) + ".png";
}

function art_url(dex) {
    return "https://www.serebii.net/pokemon/art/" + dex_pad(dex) + ".png";
}

function el(tag, className, html) {
    var dom = document.createElement(tag);
    if (className) {
        dom.className = className;
    }
    if (html !== undefined) {
        dom.innerHTML = html;
    }
    return dom;
}

/** A two-column label/value table. */
function rows(pairs) {
    var table = el("table", "sp-rows");
    for (var pair of pairs) {
        if (pair[1] === null || pair[1] === undefined) {
            continue;
        }
        var tr = el("tr");
        tr.appendChild(el("th", null, pair[0]));
        tr.appendChild(el("td", null, pair[1]));
        table.appendChild(tr);
    }
    return table;
}

function section(title, node) {
    var dom = el("div", "sp-section");
    dom.appendChild(el("h4", null, title));
    dom.appendChild(node);
    return dom;
}

/** Horizontal bar list, used for move usage. */
function bar_list(entries, unit) {
    var max = entries.length ? entries[0][1] : 1;
    var dom = el("div", "sp-bars");
    for (var entry of entries) {
        var row = el("div", "sp-bar-row");
        row.appendChild(el("span", "sp-bar-name", entry[0]));
        var track = el("span", "sp-bar-track");
        var fill = el("span", "sp-bar-fill");
        fill.style.width = Math.max(2, (100 * entry[1]) / max) + "%";
        track.appendChild(fill);
        row.appendChild(track);
        row.appendChild(el("span", "sp-bar-count", entry[1] + (unit || "")));
        dom.appendChild(row);
    }
    return dom;
}

/* -------------------------------------------------------------------- elo */

var elo_cache = null;

function rank_map(elos) {
    var keys = Object.keys(elos).sort(function (a, b) { return elos[b] - elos[a]; });
    var out = {total: keys.length};
    keys.forEach(function (key, i) {
        out[key] = {elo: elos[key], rank: i + 1};
    });
    return out;
}

/**
 * ELO is computed by the site itself (index.js `set_statistics`), not by the replay
 * parser, so it is read off the live Player/Creature objects `main()` leaves behind.
 * Player ELO is a plain number. Creature ELO is keyed by player id, so we take the
 * entry for whoever holds the creature at season end -- the same figure the Pokemon
 * Statistics table prints -- and rank only rated entries.
 */
function elo_index() {
    if (elo_cache) {
        return elo_cache;
    }
    var owner = {};
    for (var p of (window.raw && raw.players) || []) {
        for (var cid of p.creature_ids) {
            owner[cid] = p.id;
        }
    }

    var creature_elos = {};
    for (var creature of window.creatures || []) {
        if (!creature.stat || !creature.stat.elo) {
            continue;
        }
        // Deliberately the current owner's rating only, with no fallback to a
        // previous owner's: ratings are per (creature, trainer) pair, and this keeps
        // the panel agreeing with the Pokemon Statistics table's ELO column. A mon
        // traded to someone it has not yet played for reads as unrated, as it does there.
        var rating = creature.stat.elo[owner[creature.id]];
        if (typeof rating === "number") {
            creature_elos[creature.id] = rating;
        }
    }

    var player_elos = {};
    for (var player of window.players || []) {
        if (player.stat && typeof player.stat.elo === "number") {
            player_elos[player.id] = player.stat.elo;
        }
    }

    elo_cache = {creatures: rank_map(creature_elos), players: rank_map(player_elos)};
    return elo_cache;
}

/** "Season 8" from the blob's own meta, so one shared panel serves every season. */
function season_label() {
    var season = (replay_stats.meta || {}).season;
    if (!season) {
        return "this season";
    }
    var num = season.replace(/^s/, "").replace(/_half.*$/, ".5").replace(/_.*$/, "");
    return "Season " + num;
}

/**
 * Every stat on these panels is computed from the replays we actually hold, which is
 * not always the whole season -- Showdown purges old replays, and a game can simply go
 * unlinked. When that sample is partial, say so rather than letting rates read as
 * complete. `recorded` is the season's own match-record count for that entity.
 */
function coverage_note(sampled, recorded) {
    if (!recorded || sampled >= recorded) {
        return null;
    }
    var dom = el("div", "sp-coverage");
    // Capped at 99: this only renders when the sample is short, so a rounded 100%
    // would contradict the sentence it sits in (221 of 222 is not "100%").
    dom.innerHTML = "Based on <b>" + sampled + " of " + recorded + "</b> recorded games (" +
        Math.min(99, Math.round((100 * sampled) / recorded)) + "%). " + season_label() +
        " replays are incomplete, so totals below undercount and rates come from the " +
        "games we have.";
    return dom;
}

/** Headline row: rating on the left, standing on the right. */
function elo_row(entry, total) {
    if (!entry) {
        return ["ELO", "–", "unrated"];
    }
    return ["ELO", Math.round(entry.elo), "#" + entry.rank + " of " + total];
}

function player_name(player_id) {
    var player = (window.raw && raw.players || []).find(function (p) {
        return p.id === Number(player_id);
    });
    return player ? player.name : "Player " + player_id;
}

function creature_name(dex) {
    // raw.creatures is a flat national-dex-ordered name list; id is index + 1.
    var names = (window.raw && raw.creatures) || [];
    return names[Number(dex) - 1] ||
        (replay_stats.creatures[String(dex)] || {}).name ||
        "#" + dex;
}

/* ------------------------------------------------------------------ panel */

function open_panel(title, subtitle, body_nodes, hero) {
    var overlay = document.getElementById("sp-overlay");
    var panel = document.getElementById("sp-panel");
    var head = document.getElementById("sp-head");
    // A hero block (art + headline table) replaces the plain title header.
    head.style.display = hero ? "none" : "";
    document.getElementById("sp-title").innerHTML = title;
    document.getElementById("sp-subtitle").innerHTML = subtitle || "";
    var body = document.getElementById("sp-body");
    body.innerHTML = "";
    if (hero) {
        body.appendChild(hero);
    }
    for (var node of body_nodes) {
        body.appendChild(node);
    }
    overlay.classList.add("open");
    panel.scrollTop = 0;
}

/**
 * Art + identity on the left, four headline numbers on the right.
 * Pass `right_node` instead of `headline_rows` when there are no numbers to show.
 */
function hero_block(art_html, name, subtitle, types, headline_rows, right_node) {
    var hero = el("div", "sp-hero");

    var left = el("div", "sp-hero-left");
    left.innerHTML = art_html;
    left.appendChild(el("div", "sp-hero-name", name));
    if (subtitle) {
        left.appendChild(el("div", "sp-hero-num", subtitle));
    }
    if (types && types.length) {
        var type_row = el("div", "sp-types");
        for (var type of types) {
            type_row.appendChild(el("span", "sp-type sp-type-" + type.toLowerCase(), type));
        }
        left.appendChild(type_row);
    }
    hero.appendChild(left);

    var right = el("div", "sp-hero-right");
    if (right_node) {
        right.appendChild(right_node);
    } else {
        var table = el("table", "sp-headline");
        for (var row of headline_rows) {
            var tr = el("tr");
            tr.appendChild(el("th", null, row[0]));
            tr.appendChild(el("td", "sp-h-main", row[1]));
            tr.appendChild(el("td", "sp-h-alt", row[2]));
            table.appendChild(tr);
        }
        right.appendChild(table);
    }
    hero.appendChild(right);
    return hero;
}

function close_panel() {
    document.getElementById("sp-overlay").classList.remove("open");
}

/* ------------------------------------------------------------ pokemon view */

function show_creature(dex) {
    var stats = replay_stats.creatures[String(dex)];
    var name = creature_name(dex);
    var bulbapedia = "https://bulbapedia.bulbagarden.net/wiki/" + name.replace(/ /g, "_");
    var art = '<img class="sp-art" src="' + art_url(dex) + '">';
    var types = (stats && stats.types) || (replay_stats.dex_types || {})[String(dex)] || [];
    var foot = el("p", "sp-foot", '<a href="' + bulbapedia + '" target="_blank">Bulbapedia &rarr;</a>');

    if (!stats) {
        var message = el("div");
        message.appendChild(el("p", "sp-empty",
            "This Pokemon never appeared in a " + season_label() + " replay. " +
            "It may have been drafted but never brought to a match."));
        message.appendChild(foot);
        open_panel("", "", [], hero_block(art, name, "#" + dex, types, null, message));
        return;
    }

    // Rating first, then one number each for overall, offence, defence and support.
    var creature_elo = elo_index().creatures;
    var hero = hero_block(art, name, "#" + dex, types, [
        elo_row(creature_elo[dex], creature_elo.total),
        ["Games won", stats.wins, percent(stats.wins, stats.games) + " of " + stats.games],
        ["KOs", stats.kos, per_game(stats.kos, stats.games) + " / game"],
        ["Deaths", stats.fainted, ratio(stats.kos, stats.fainted) + " KO ratio"],
        ["Support moves", stats.support_moves_used,
            percent(stats.support_moves_used, stats.moves_used) + " of moves"],
    ]);

    var nodes = [];

    // A Pokemon has no match records of its own, so the season's coverage applies.
    var season_note = coverage_note((replay_stats.meta || {}).battles,
                                    (replay_stats.meta || {}).recorded_matches);
    if (season_note) {
        nodes.push(season_note);
    }

    if (stats.top_moves.length) {
        nodes.push(section("Most used moves", bar_list(stats.top_moves)));
    }

    nodes.push(section("Offensive stats", rows([
        ["HP bars dealt", bars(stats.pct_dealt) +
            " <span class='sp-dim'>(" + stats.dmg_dealt.toLocaleString() + " raw HP)</span>"],
        ["Damage per turn on field", ratio(stats.pct_dealt / 100, stats.turns_active) + " bars"],
        ["Net damage traded", bars(stats.pct_dealt - stats.pct_taken) + " bars"],
        ["KOs", stats.kos],
        ["Attacking moves used", stats.damaging_moves_used],
        ["Super effective hits", stats.se_hits],
        ["Resisted hits", stats.resisted_hits],
        ["Misses", stats.misses + " <span class='sp-dim'>(" +
            percent(stats.misses, stats.moves_used) + " of moves)</span>"],
        ["Immune / no effect", stats.immune],
        ["Crits landed", stats.crits_landed +
            (stats.crits_landed !== stats.crits_landed_luck
                ? " <span class='sp-dim'>(" + stats.crits_landed_luck + " excluding always-crit moves)</span>"
                : "")],
    ])));

    nodes.push(section("Defensive stats", rows([
        ["HP bars taken", bars(stats.pct_taken) +
            " <span class='sp-dim'>(" + stats.dmg_taken.toLocaleString() + " raw HP)</span>"],
        ["Damage absorbed per death", ratio((stats.pct_taken + stats.pct_healed) / 100, stats.fainted) + " bars"],
        ["Deaths", stats.fainted],
        ["Survived to the end", stats.games - stats.fainted +
            " <span class='sp-dim'>of " + stats.games + " games</span>"],
        ["Crits taken", stats.crits_taken],
        ["Stat drops suffered", stats.unboosts_taken],
        ["Statuses suffered", stats.statuses_taken],
    ])));

    nodes.push(section("Support stats", rows([
        ["HP bars healed", bars(stats.pct_healed) +
            " <span class='sp-dim'>(" + stats.healed.toLocaleString() + " raw HP)</span>"],
        ["Support moves used", stats.support_moves_used +
            " <span class='sp-dim'>(" + percent(stats.support_moves_used, stats.moves_used) + " of moves)</span>"],
        ["Stat boosts gained", stats.boosts],
        ["Statuses inflicted", stats.statuses_inflicted],
    ])));

    var owners = Object.keys(stats.by_player).map(function (pid) {
        return '<span class="stat-link sp-inline" data-player="' + pid + '">' +
            player_name(pid) + "</span> (" + stats.by_player[pid] + "g)";
    }).join(", ");

    nodes.push(section("Deployment", rows([
        ["Owned by", owners || "–"],
        ["Times sent out", stats.times_sent_out],
        ["Times switched out", stats.switched_out],
        ["Turns on field", stats.turns_active +
            " <span class='sp-dim'>(" + per_game(stats.turns_active, stats.games) + " / game)</span>"],
        ["Terastallised", stats.tera],
        ["Mega evolved", stats.mega],
        ["Items consumed", stats.items_lost],
        ["Forms seen", stats.forms.map(function (f) { return f[0] + " ×" + f[1]; }).join(", ")],
        ["Nicknames", stats.nicknames.map(function (n) { return n[0]; }).join(", ")],
        stats.items.length
            ? ["Items revealed", stats.items.map(function (i) { return i[0] + " ×" + i[1]; }).join(", ")] : null,
        stats.abilities.length
            ? ["Abilities revealed", stats.abilities.map(function (a) { return a[0] + " ×" + a[1]; }).join(", ")] : null,
        // Every battle is level 100, so max HP exactly pins down HP EV/IV investment.
        stats.maxhps.length
            ? ["Max HP seen", stats.maxhps.map(function (h) { return h[0] + " ×" + h[1]; }).join(", ")] : null,
    ].filter(Boolean))));

    nodes.push(foot);

    open_panel("", "", nodes, hero);
}

/* ------------------------------------------------------------- player view */

function show_player(player_id) {
    var stats = replay_stats.players[String(player_id)];
    var name = player_name(player_id);
    var player = (window.raw && raw.players || []).find(function (p) {
        return p.id === Number(player_id);
    });
    var art = player && player.trainer_sprite
        ? '<img class="sp-trainer" src="' + player.trainer_sprite + '">' : "";

    if (!stats) {
        var message = el("p", "sp-empty", "No " + season_label() + " replays are linked to this trainer.");
        open_panel("", "", [], hero_block(art, name, "", null, null, message));
        return;
    }

    // Their three most-played Pokemon stand in for the type badges. Clickable.
    var signature = Object.keys(replay_stats.creatures)
        .filter(function (dex) { return replay_stats.creatures[dex].by_player[String(player_id)]; })
        .sort(function (a, b) {
            return replay_stats.creatures[b].by_player[String(player_id)] -
                   replay_stats.creatures[a].by_player[String(player_id)];
        })
        .slice(0, 3);
    var badges = el("div", "sp-hero-mons", signature.map(function (dex) {
        var mon = replay_stats.creatures[dex];
        return '<img class="sp-hero-mon stat-link" data-dex="' + dex +
            '" title="' + mon.name + " — " + mon.by_player[String(player_id)] +
            ' games" src="' + sprite_url(dex) + '">';
    }).join(""));

    var player_elo = elo_index().players;
    var hero = hero_block(art, name,
        stats.wins + "–" + (stats.games - stats.wins) + " in " + season_label(), null, [
            elo_row(player_elo[player_id], player_elo.total),
            ["Games won", stats.wins, percent(stats.wins, stats.games) + " of " + stats.games],
            ["KOs", stats.kos, per_game(stats.kos, stats.games) + " / game"],
            ["Mons lost", stats.fainted, ratio(stats.kos, stats.fainted) + " KO ratio"],
            ["Support moves", stats.support_moves_used,
                percent(stats.support_moves_used, stats.moves_used) + " of moves"],
        ]);
    if (signature.length) {
        hero.querySelector(".sp-hero-left").appendChild(badges);
    }

    var nodes = [];

    // Trainers have their own match-record count, so their coverage is exact.
    var player_note = coverage_note(stats.games, stats.recorded_games);
    if (player_note) {
        nodes.push(player_note);
    }

    if (stats.top_moves.length) {
        nodes.push(section("Most used moves", bar_list(stats.top_moves)));
    }

    nodes.push(section("Offensive stats", rows([
        ["HP bars dealt", bars(stats.pct_dealt) +
            " <span class='sp-dim'>(" + stats.dmg_dealt.toLocaleString() + " raw HP)</span>"],
        ["Damage per game", per_game(stats.pct_dealt / 100, stats.games) + " bars"],
        ["Net damage traded", bars(stats.pct_dealt - stats.pct_taken) + " bars"],
        ["KOs scored", stats.kos],
        ["Attacking moves used", stats.damaging_moves_used],
        ["Super effective hits", stats.se_hits],
        ["Resisted hits", stats.resisted_hits],
        ["Misses", stats.misses + " <span class='sp-dim'>(" +
            percent(stats.misses, stats.moves_used) + " of moves)</span>"],
        ["Immune / no effect", stats.immune],
        ["Crits landed", stats.crits_landed],
    ])));

    nodes.push(section("Defensive stats", rows([
        ["HP bars taken", bars(stats.pct_taken) +
            " <span class='sp-dim'>(" + stats.dmg_taken.toLocaleString() + " raw HP)</span>"],
        ["Damage taken per game", per_game(stats.pct_taken / 100, stats.games) + " bars"],
        ["Pokemon lost", stats.fainted +
            " <span class='sp-dim'>(" + per_game(stats.fainted, stats.games) + " / game)</span>"],
        ["Crits taken", stats.crits_taken],
        ["Stat drops suffered", stats.unboosts_taken],
        ["Statuses suffered", stats.statuses_taken],
    ])));

    var support_rows = rows([
        ["HP bars healed", bars(stats.pct_healed) +
            " <span class='sp-dim'>(" + stats.healed.toLocaleString() + " raw HP)</span>"],
        ["Support moves used", stats.support_moves_used +
            " <span class='sp-dim'>(" + percent(stats.support_moves_used, stats.moves_used) + " of moves)</span>"],
        ["Stat boosts gained", stats.boosts],
        ["Statuses inflicted", stats.statuses_inflicted],
    ]);
    var support = section("Support stats", support_rows);
    if (stats.hazards.length) {
        support.appendChild(el("div", "sp-subhead", "Screens, hazards &amp; field control"));
        support.appendChild(bar_list(stats.hazards));
    }
    nodes.push(support);

    // Crit differential is the closest thing to a luck stat. Always-crit moves
    // (Surging Strikes, Wicked Blow, ...) are excluded or it just measures movesets.
    var crit_diff = stats.crits_landed_luck - stats.crits_taken;
    nodes.push(section("Luck ledger", rows([
        ["Moves used", stats.moves_used],
        ["Crits landed", stats.crits_landed_luck + " <span class='sp-dim'>(" +
            percent(stats.crits_landed_luck, stats.moves_used) + " of moves, always-crit moves excluded)</span>"],
        ["Crits taken", stats.crits_taken],
        ["Crit differential", (crit_diff > 0 ? "+" : "") + crit_diff +
            (crit_diff < 0 ? " <span class='sp-dim'>(unlucky)</span>"
                           : crit_diff > 0 ? " <span class='sp-dim'>(lucky)</span>" : "")],
        ["Misses", stats.misses + " <span class='sp-dim'>(" + percent(stats.misses, stats.moves_used) + " of moves)</span>"],
    ])));

    var teras = stats.tera_turns || [];
    nodes.push(section("Playstyle &amp; pace", rows([
        // Only pivots count: bringing in a replacement after a KO is not a decision.
        ["Voluntary switches per game", per_game(stats.switches, stats.games) +
            " <span class='sp-dim'>(" + stats.switches + " total, excludes post-KO replacements)</span>"],
        ["Moves per game", per_game(stats.moves_used, stats.games)],
        ["Turns per game", per_game(stats.turns, stats.games)],
        ["Average game length", clock(stats.seconds / Math.max(1, stats.games))],
        ["Seconds per turn", stats.turns ? (stats.seconds / stats.turns).toFixed(0) + "s" : "–"],
        ["Terastallised", teras.length
            ? teras.length + " times, average turn " + mean(teras).toFixed(1) +
              " <span class='sp-dim'>(earliest T" + teras[0] + ", latest T" + teras[teras.length - 1] + ")</span>"
            : "never"],
        ["Mega evolved", stats.mega],
        ["Chat messages", stats.chat],
    ])));

    var h2h_keys = Object.keys(stats.h2h);
    if (h2h_keys.length) {
        var table = el("table", "sp-rows");
        for (var pid of Object.keys(replay_stats.players)) {
            if (pid === String(player_id)) {
                continue;
            }
            var won = stats.h2h[pid] || 0;
            var lost = (replay_stats.players[pid].h2h || {})[String(player_id)] || 0;
            var tr = el("tr");
            tr.appendChild(el("th", null,
                '<span class="stat-link sp-inline" data-player="' + pid + '">' + player_name(pid) + "</span>"));
            tr.appendChild(el("td", null, won + " – " + lost +
                ' <span class="sp-dim">(' + percent(won, won + lost) + ")</span>"));
            table.appendChild(tr);
        }
        nodes.push(section("Head to head", table));
    }

    // Which of this trainer's Pokemon pulled their weight.
    var roster = Object.keys(replay_stats.creatures).filter(function (dex) {
        return replay_stats.creatures[dex].by_player[String(player_id)];
    }).sort(function (a, b) {
        return replay_stats.creatures[b].pct_dealt - replay_stats.creatures[a].pct_dealt;
    });
    if (roster.length) {
        var roster_table = el("table", "sp-rows sp-roster");
        var head = el("tr");
        for (var label of ["Pokemon", "G", "Dealt", "Taken", "KOs", "Lost", "KO/loss"]) {
            head.appendChild(el("th", null, label));
        }
        roster_table.appendChild(head);
        for (var dex of roster) {
            var c = replay_stats.creatures[dex];
            var tr2 = el("tr");
            tr2.appendChild(el("td", null,
                '<img class="sp-mini" src="' + sprite_url(dex) + '">' +
                '<span class="stat-link sp-inline" data-dex="' + dex + '">' + c.name + "</span>"));
            tr2.appendChild(el("td", null, c.by_player[String(player_id)]));
            tr2.appendChild(el("td", null, bars(c.pct_dealt)));
            tr2.appendChild(el("td", null, bars(c.pct_taken)));
            tr2.appendChild(el("td", null, c.kos));
            tr2.appendChild(el("td", null, c.fainted));
            tr2.appendChild(el("td", null, ratio(c.kos, c.fainted)));
            roster_table.appendChild(tr2);
        }
        nodes.push(section("Roster — by HP bars dealt", roster_table));
    }

    open_panel("", "", nodes, hero);
}

/* ----------------------------------------------------------------- wiring */

function init_stats_panel() {
    // Seasons predating the replay archive (s1-s6) ship no replay_stats.js at all, and
    // s6's replays were purged before they could be saved. index.js still marks every
    // sprite as a stat-link, so without this the affordances would be live and clicking
    // would throw. Bail out and let the CSS drop the pointer/hover cues.
    if (typeof replay_stats === "undefined" || !replay_stats || !replay_stats.meta) {
        document.body.classList.add("no-replay-stats");
        return;
    }

    var overlay = el("div", "sp-overlay");
    overlay.id = "sp-overlay";
    overlay.innerHTML =
        '<div class="sp-panel" id="sp-panel">' +
        '  <button class="sp-close" id="sp-close" title="Close">&times;</button>' +
        '  <div class="sp-head" id="sp-head"><h3 id="sp-title"></h3><div class="sp-sub" id="sp-subtitle"></div></div>' +
        '  <div class="sp-body" id="sp-body"></div>' +
        "</div>";
    document.body.appendChild(overlay);

    document.getElementById("sp-close").addEventListener("click", close_panel);
    overlay.addEventListener("click", function (event) {
        if (event.target === overlay) {
            close_panel();
        }
    });
    document.addEventListener("keydown", function (event) {
        if (event.key === "Escape") {
            close_panel();
        }
    });

    // Delegated so it also covers links rendered inside the panel itself.
    document.addEventListener("click", function (event) {
        var target = event.target.closest(".stat-link");
        if (!target) {
            return;
        }
        if (target.hasAttribute("data-dex")) {
            event.preventDefault();
            show_creature(target.getAttribute("data-dex"));
        } else if (target.hasAttribute("data-player")) {
            event.preventDefault();
            show_player(target.getAttribute("data-player"));
        }
    });
}
